// Example usage of the Audio Babel Record Store index system
// This file demonstrates how to use the position encoding and parsing services

import { parseIndex, getIndexPreview } from '../src/services/indexParser.js';
import { 
    getPositionFromIndex, 
    formatAddress,
    calculateRoomId,
    TRACKS_PER_ROOM 
} from '../src/services/positionEncoder.js';
import { 
    calculateIndexSize, 
    getRecommendedSettings,
    formatDuration 
} from '../src/services/audioConstraints.js';
import Room from '../src/models/Room.js';
import Wall from '../src/models/Wall.js';
import Shelf from '../src/models/Shelf.js';
import Track from '../src/models/Track.js';

console.log('=== Audio Babel Record Store - Index System Example ===\n');

// Example 1: Get recommended audio settings
console.log('1. Recommended Audio Settings:');
const settings = getRecommendedSettings();
console.log(JSON.stringify(settings, null, 2));
console.log();

// Example 2: Calculate expected index size
console.log('2. Calculate Index Size for Different Durations:');
[30, 60, 90, 120].forEach(duration => {
    const size = calculateIndexSize(duration);
    console.log(`  ${duration}s audio: ${size.base64Length} characters (~${size.estimatedFileSizeMB.toFixed(2)} MB)`);
});
console.log();

// Example 3: Parse a sample index
console.log('3. Parse Sample Index:');
// This would be generated by the C++ library from actual audio
const sampleIndex = "dGVzdC1hdWRpby1pbmRleC1leGFtcGxl";
console.log(`  Input: ${sampleIndex}`);
console.log(`  Preview: ${getIndexPreview(sampleIndex, 16)}`);

const parsed = parseIndex(sampleIndex);
console.log(`  Room ID: ${parsed.position.roomId}`);
console.log(`  Position: Wall ${parsed.position.wall}, Shelf ${parsed.position.shelf}, Track ${parsed.position.track}`);
console.log(`  Address: ${parsed.position.address}`);
console.log(`  Metadata:`);
console.log(`    Genre:  ${parsed.metadata.genre}`);
console.log(`    Artist: ${parsed.metadata.artist}`);
console.log(`    Album:  ${parsed.metadata.album}`);
console.log(`    Track:  ${parsed.metadata.track}`);
console.log();

// Example 4: Create a complete library structure
console.log('4. Create Library Structure:');

// Create room
const room = new Room(parsed.position.roomId, parsed.metadata.genre);
console.log(`  Created room: ${room.roomId} (Genre: ${room.genreLabel})`);

// Create wall
const wall = new Wall(parsed.position.wall, parsed.metadata.artist);
console.log(`  Created wall ${wall.wallNumber} (Artist: ${wall.artistLabel})`);

// Create shelf
const shelf = new Shelf(parsed.position.shelf, parsed.metadata.album);
console.log(`  Created shelf ${shelf.shelfNumber} (Album: ${shelf.albumLabel})`);

// Create track (using sample duration)
const track = new Track(
    parsed.index,
    parsed.position,
    parsed.metadata,
    95.5,  // duration in seconds
    null   // coverSvg (would be generated by C++ library)
);
console.log(`  Created track ${track.trackNumber} (Duration: ${track.formatDuration()})`);

// Assemble the structure
shelf.setTrack(parsed.position.track, track);
wall.setShelf(parsed.position.shelf, shelf);
room.setWall(parsed.position.wall, wall);

console.log(`  Assembled structure: ${track.getFullPath()}`);
console.log();

// Example 5: Navigate the structure
console.log('5. Navigate to Track:');
const foundTrack = room
    .getWall(parsed.position.wall)
    .getShelf(parsed.position.shelf)
    .getTrack(parsed.position.track);

if (foundTrack) {
    console.log(`  ✓ Found track at ${foundTrack.address}`);
    console.log(`  Details: ${foundTrack.getTrackDetails()}`);
} else {
    console.log(`  ✗ Track not found`);
}
console.log();

// Example 6: Room statistics
console.log('6. Room Statistics:');
console.log(`  Room ID: ${room.roomId}`);
console.log(`  Populated walls: ${room.getPopulatedWalls().length}/4`);
console.log(`  Total tracks: ${room.getTrackCount()}/${TRACKS_PER_ROOM}`);
console.log(`  Is full: ${room.isFull()}`);
console.log();

// Example 7: Multiple tracks with different positions
console.log('7. Simulate Multiple Tracks:');
const sampleIndexes = [
    "YW5vdGhlci10ZXN0LWluZGV4",
    "eWV0LWFub3RoZXItaW5kZXg",
    "bW9yZS10ZXN0LWRhdGE"
];

sampleIndexes.forEach((idx, i) => {
    const pos = getPositionFromIndex(idx);
    console.log(`  Track ${i + 1}: ${getIndexPreview(idx, 12)} → ${pos.address}`);
});
console.log();

// Example 8: Address formatting
console.log('8. Address Formats:');
const addresses = [
    formatAddress("room_abc12345", 1, 1, 1),    // First track
    formatAddress("room_abc12345", 4, 20, 32),  // Last track
    formatAddress("room_abc12345", 2, 10, 16),  // Middle track
];

addresses.forEach(addr => {
    console.log(`  ${addr}`);
});
console.log();

console.log('=== Example Complete ===');
console.log('\nTo use this system:');
console.log('1. Generate audio indexes using the C++ library');
console.log('2. Parse indexes with parseIndex() to get position and metadata');
console.log('3. Create Track objects and place them in the library structure');
console.log('4. Navigate using room.getWall().getShelf().getTrack()');
console.log('\nSee INDEX_ARCHITECTURE.md for full documentation.');
